const elBurger = document.querySelector('.header__burger')
const elStick1 = document.querySelector('.header__burger__stick1')
const elStick2 = document.querySelector('.header__burger__stick2')
const elStick3 = document.querySelector('.header__burger__stick3')
const elBurger2 = document.querySelector('.header__burger_2')
const elStick4 = document.querySelector('.header__burger_2__stick1')
const elStick5 = document.querySelector('.header__burger_2__stick2')
const elStick6 = document.querySelector('.header__burger_2__stick3')
const elLink1 = document.querySelector('.header__user__link1')
const elLink2 = document.querySelector('.header__user__link2')
const elLink3 = document.querySelector('.header__user__link3')

const elModal = document.querySelector('.modal')
const elUser = document.querySelector('.header__user')
const elList = document.querySelector('.header__list')

elBurger.addEventListener('click',function(){
  elStick1.classList.toggle('active__stcik1')
  elStick2.classList.toggle('active__stcik2')
  elStick3.classList.toggle('active__stcik3')
  elModal.classList.toggle('active__modal')
  elUser.classList.toggle('active__user')
  elList.classList.toggle('active__list')
})
elBurger2.addEventListener('click',function(){
  elStick4.classList.toggle('active__stcik1')
  elStick5.classList.toggle('active__stcik2')
  elStick6.classList.toggle('active__stcik3')
  elLink1.classList.toggle('active__user__link1')
  elLink2.classList.toggle('active__user__link2')
  elLink3.classList.toggle('active__user__link3')
})
